P34: [/] Changement du fonctionnement de la classe ItemMixin pour fix un bug
[/] Fix 
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.InteractionResultHolder.getObject()" because "interactionresultholder" is null